### ISSUE TITLE
怎么换成 isr渲染的呀大佬

### ISSUE THREAD

**Issue by pengxinseo** [orangejuice/blog#5]
大佬

**Comment by orangejuice** [comment]
不是大佬，就瞎写。。Next.js（App dir）用getStaticProps方法可以传递静态生成page用的参数
https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#static-site-generation-getstaticprops
https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#incremental-static-regeneration-getstaticprops-with-revalidate
