### ISSUE TITLE
支持  cloudflare page部署么 

### ISSUE THREAD

**Issue by pengxinseo** [orangejuice/blog#8]
我研究了 三四天没发现 支持 多语言 mdx  blog  部署在  cloudflare page的

**Comment by orangejuice** [comment]
我用的Vercel。之前了解了一下要部署next.js项目到cloudflarepage上面的话需要额外做一些配置和调试，可能很多坑，暂时没有搞。

最近一个挺火的blog项目 https://github.com/OXeu/Rin，它是部署到cloudflare pages的，刚看了一眼竟然1k多星了
